
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - workloads.k8s.coraiberkleid.xyz
  resources:
  - websvcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.k8s.coraiberkleid.xyz
  resources:
  - websvcs/status
  verbs:
  - get
  - patch
  - update
