# permissions for end users to view websvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: websvc-viewer-role
rules:
- apiGroups:
  - workloads.k8s.coraiberkleid.xyz
  resources:
  - websvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workloads.k8s.coraiberkleid.xyz
  resources:
  - websvcs/status
  verbs:
  - get
